// Dotted world map, packed as a land mask.
//
// Source geometry was a 1235x452 dotted-map SVG whose dots sit on a 7px
// lattice. Snapping to that lattice gives a 176x65 grid; one bit per cell,
// base64-encoded, is ~1.9KB instead of the 891KB the original SVG cost.
// Bit order is little-endian within each byte, cells in row-major order.

export const MAP_COLS = 176;
export const MAP_ROWS = 65;
export const MAP_ASPECT = 1235 / 452;

const MASK_B64 =
  "AAAAAAAA+MAPAAAAAAAAAAAAAAAAAAAAAAAAAN7/DwADADAAAAAAAAAAAAAAAAAAAADy/w/AAwAADwAAAAAAAAAAAAAAAAAA" +
  "AP8HAAAY4A+AAAAAAAAAAAAAAAAYwAH/AwAAiP3/jwMAAAAAAAAAAP77LIKD3wGAP2D///v/fwAAAAAAAID//f8Lwx8AwH//" +
  "//7///8DAAAAAADg//9/wcEDB+C///3//9//EwAAAAAA/L//H4DAAQD4/t///+///w8AAAAAAG7+fw8YgAAA+P77/3///x2H" +
  "AAAAAAAG7P8HfAAAAGD8/v/7//eBARcAAAAAAPz7D3oAAEBw/v5//7//ARZcAAAAAAD6f5/fAQCw8H//7//7fw/WaQAAAAAA" +
  "fv+P/wAA0Pq///t///c/QA8AAAAAAP3vf0cAAAD73//973//t0AAAAAAAADff//DAADA9+///vvff/+IDQQAAABA//33BwAA" +
  "gPevvv/++/df8G5sAAAA4PfvPwAAALCnL9x/f//9faq7uwEAALC/fx8AAADwQbbp39+/vz+ABe4BAAD4/f0LAAAA+JDi9+/v" +
  "7+8nCAA0AQAA2N/vAQAAAHBA5Pv3+/v7bRAAghwAAPh+fwEAAACAFxD6+/3+fo8dIDp2AADs93sAAAAA6BcA/P1+v98XAMD9" +
  "uwAA+N8vAAAAANx3Cvx+3+/3PQAAFwwAAPR/CQAAAADc9/t9ve/3fX8AABoUAADwBwgAAACA3+/7vN33fd93AAAAOgAA5AEA" +
  "AAAAwL7v+7rj+77vfQAAAFwAALBBGAAAAMAFwHvbd3Dv+14BAAAEAADwMkAAAADA/e9913vAd7wPAAAAAAAAwBsAAAAAwH3v" +
  "fe97gDvYAQAAAAAAOABuAAAAANB7772XPYAd8AYEAAAAAG4AXAAAAADAe++99x4ADkAPCAAAAAB8ADBIAAAAwHvvvXcAAA6A" +
  "FxAAAAAA9gAg3AMAAID37t17DwAUgDxAAAAAAN4AwL0HAACA9+7dewcAOIAISAAAAAB8AAB3bwAAADfu3bsHAAAAAoABAAAA" +
  "LgAA794AAAAA6N29AwAAAAoaAAAAABkAwN3dAAAAAODevQEAAAAPHggAAAA0AMC7uwEAAADo3t0AAAAAFHYIAAAAGgBgd3cH" +
  "AAAA6N5dAAAAADCagQoAAAAA4O7ubgAAAODuLgAAAABQgAFdCAAAANDd3d0AAADA7i4AAAAAgAAAcCUAAACgu929AAAAwO4u" +
  "AAAAAAAUALADAAAAYLe7uwAAAMDubgAAAAAAAAgADAAAAMBudzcAAADA7nYAAAAAAAAARgAAAADA7W4XAAAAwO52EAAAAAAA" +
  "IIMBAAAAgNvtDgAAAOBudxgAAAAAANAOAwAAAAC62w0AAADAbhcaAAAAAABotwMAAAAAdrsNAAAAwG4HCgAAAAAAttsOAAAA" +
  "AG23CwAAAIBuCwwAAAAAgNtuFwIAAADdbgAAAACAdgsMAAAAAMBtt10EAAAA220AAAAAgHYDAAAAAADAdtttAAAAgLZdAAAA" +
  "AIB2AwAAAAAAQNttuwAAAIBuGwAAAAAAtgEAAAAAAIDdtt0AAAAAbxcAAAAAALYAAAAAAACAbtt2AAAAAPsHAAAAAAA2AAAA" +
  "AAAAAAdIWwAAAIC2AQAAAAAAAAAAAAAAAAAAgC0AAACALQAAAAAAAAAAAAAAAAAAAIAWAAAAAA0AAAAAAAAAAAAAAAAAAAAA" +
  "AIAAAAALAAAAAAAAAAAAAAAAAAAAAAQgAAAACwAAAAAAAAAAAAAAAAAAAAAAGAAAgBYAAAAAAAAAAAAAAAAAAAAAAAYAAAAF" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAABAEAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAA=";

/** Decoded land cells as [col, row] pairs. Computed once at module load. */
export function landCells(): Array<[number, number]> {
  const bin = atob(MASK_B64);
  const cells: Array<[number, number]> = [];
  for (let i = 0; i < MAP_COLS * MAP_ROWS; i++) {
    if (bin.charCodeAt(i >> 3) & (1 << (i & 7))) {
      cells.push([i % MAP_COLS, Math.floor(i / MAP_COLS)]);
    }
  }
  return cells;
}
